import type { CountyMetric, HomeType, VelocityTier } from "~components/heatmap/types";

function tier(rate: number): VelocityTier {
  if (rate >= 10) return "high";
  if (rate >= 5) return "medium";
  return "low";
}

// SFH mock data — realistic Florida new construction numbers (March 2026)
const SFH_DATA: Array<Omit<CountyMetric, "velocityTier">> = [
  {
    county: "Orange",
    absorptionRate: 11.2,
    absorptionRatePrevMonth: 10.8,
    medianClosePrice: 432000,
    medianClosePricePrevMonth: 422000,
    activeInventory: 420,
    closedSalesThisMonth: 53,
  },
  {
    county: "Hillsborough",
    absorptionRate: 10.5,
    absorptionRatePrevMonth: 10.1,
    medianClosePrice: 448000,
    medianClosePricePrevMonth: 438000,
    activeInventory: 390,
    closedSalesThisMonth: 46,
  },
  {
    county: "St. Johns",
    absorptionRate: 13.4,
    absorptionRatePrevMonth: 12.8,
    medianClosePrice: 549000,
    medianClosePricePrevMonth: 537000,
    activeInventory: 385,
    closedSalesThisMonth: 58,
  },
  {
    county: "Polk",
    absorptionRate: 12.1,
    absorptionRatePrevMonth: 11.5,
    medianClosePrice: 322000,
    medianClosePricePrevMonth: 315000,
    activeInventory: 480,
    closedSalesThisMonth: 66,
  },
  {
    county: "Duval",
    absorptionRate: 10.2,
    absorptionRatePrevMonth: 9.8,
    medianClosePrice: 414000,
    medianClosePricePrevMonth: 406000,
    activeInventory: 445,
    closedSalesThisMonth: 51,
  },
  {
    county: "Osceola",
    absorptionRate: 9.1,
    absorptionRatePrevMonth: 8.6,
    medianClosePrice: 381000,
    medianClosePricePrevMonth: 373000,
    activeInventory: 280,
    closedSalesThisMonth: 28,
  },
  {
    county: "Pasco",
    absorptionRate: 9.3,
    absorptionRatePrevMonth: 8.8,
    medianClosePrice: 364000,
    medianClosePricePrevMonth: 356000,
    activeInventory: 350,
    closedSalesThisMonth: 36,
  },
  {
    county: "Clay",
    absorptionRate: 9.6,
    absorptionRatePrevMonth: 9.1,
    medianClosePrice: 400000,
    medianClosePricePrevMonth: 391000,
    activeInventory: 240,
    closedSalesThisMonth: 26,
  },
  {
    county: "Seminole",
    absorptionRate: 9.8,
    absorptionRatePrevMonth: 9.2,
    medianClosePrice: 467000,
    medianClosePricePrevMonth: 458000,
    activeInventory: 210,
    closedSalesThisMonth: 23,
  },
  {
    county: "Manatee",
    absorptionRate: 8.9,
    absorptionRatePrevMonth: 8.4,
    medianClosePrice: 499000,
    medianClosePricePrevMonth: 489000,
    activeInventory: 235,
    closedSalesThisMonth: 23,
  },
  {
    county: "Flagler",
    absorptionRate: 8.8,
    absorptionRatePrevMonth: 8.3,
    medianClosePrice: 393000,
    medianClosePricePrevMonth: 386000,
    activeInventory: 165,
    closedSalesThisMonth: 16,
  },
  {
    county: "Lake",
    absorptionRate: 8.4,
    absorptionRatePrevMonth: 8.0,
    medianClosePrice: 391000,
    medianClosePricePrevMonth: 383000,
    activeInventory: 290,
    closedSalesThisMonth: 27,
  },
  {
    county: "St. Lucie",
    absorptionRate: 8.2,
    absorptionRatePrevMonth: 7.8,
    medianClosePrice: 381000,
    medianClosePricePrevMonth: 373000,
    activeInventory: 245,
    closedSalesThisMonth: 22,
  },
  {
    county: "Brevard",
    absorptionRate: 7.8,
    absorptionRatePrevMonth: 7.2,
    medianClosePrice: 356000,
    medianClosePricePrevMonth: 349000,
    activeInventory: 320,
    closedSalesThisMonth: 27,
  },
  {
    county: "Hernando",
    absorptionRate: 7.1,
    absorptionRatePrevMonth: 6.8,
    medianClosePrice: 309000,
    medianClosePricePrevMonth: 303000,
    activeInventory: 195,
    closedSalesThisMonth: 15,
  },
  {
    county: "Nassau",
    absorptionRate: 7.2,
    absorptionRatePrevMonth: 6.9,
    medianClosePrice: 486000,
    medianClosePricePrevMonth: 478000,
    activeInventory: 120,
    closedSalesThisMonth: 10,
  },
  {
    county: "Indian River",
    absorptionRate: 6.5,
    absorptionRatePrevMonth: 6.1,
    medianClosePrice: 426000,
    medianClosePricePrevMonth: 419000,
    activeInventory: 180,
    closedSalesThisMonth: 13,
  },
  {
    county: "Volusia",
    absorptionRate: 7.5,
    absorptionRatePrevMonth: 7.0,
    medianClosePrice: 370000,
    medianClosePricePrevMonth: 362000,
    activeInventory: 275,
    closedSalesThisMonth: 22,
  },
  {
    county: "Alachua",
    absorptionRate: 5.5,
    absorptionRatePrevMonth: 5.2,
    medianClosePrice: 343000,
    medianClosePricePrevMonth: 336000,
    activeInventory: 155,
    closedSalesThisMonth: 9,
  },
  {
    county: "Sumter",
    absorptionRate: 5.2,
    absorptionRatePrevMonth: 5.5,
    medianClosePrice: 299000,
    medianClosePricePrevMonth: 295000,
    activeInventory: 175,
    closedSalesThisMonth: 10,
  },
  {
    county: "Citrus",
    absorptionRate: 4.8,
    absorptionRatePrevMonth: 5.1,
    medianClosePrice: 286000,
    medianClosePricePrevMonth: 281000,
    activeInventory: 130,
    closedSalesThisMonth: 7,
  },
  {
    county: "Marion",
    absorptionRate: 4.2,
    absorptionRatePrevMonth: 4.6,
    medianClosePrice: 279000,
    medianClosePricePrevMonth: 273000,
    activeInventory: 210,
    closedSalesThisMonth: 10,
  },
  {
    county: "Baker",
    absorptionRate: 3.8,
    absorptionRatePrevMonth: 4.2,
    medianClosePrice: 266000,
    medianClosePricePrevMonth: 261000,
    activeInventory: 75,
    closedSalesThisMonth: 3,
  },
];

// Townhome: ~12% lower prices, slightly different absorption profile
const TOWNHOME_DATA: Array<Omit<CountyMetric, "velocityTier">> = SFH_DATA.map((entry) => ({
  ...entry,
  absorptionRate: Math.round(entry.absorptionRate * 0.88 * 10) / 10,
  absorptionRatePrevMonth: Math.round(entry.absorptionRatePrevMonth * 0.88 * 10) / 10,
  medianClosePrice: Math.round((entry.medianClosePrice * 0.88) / 1000) * 1000,
  medianClosePricePrevMonth: Math.round((entry.medianClosePricePrevMonth * 0.88) / 1000) * 1000,
  activeInventory: Math.round(entry.activeInventory * 0.4),
  closedSalesThisMonth: Math.round(entry.closedSalesThisMonth * 0.4),
}));

export function getMockCountyMetrics(homeType: HomeType): CountyMetric[] {
  const base = homeType === "townhome" ? TOWNHOME_DATA : SFH_DATA;
  return base.map((entry) => ({ ...entry, velocityTier: tier(entry.absorptionRate) }));
}
